source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.5"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors", "~> 2.0"

gem "jwt", "~> 2.7"
gem "bcrypt", "~> 3.1"

gem "rails_param", "~> 1.3"

gem "draper", "~> 4.0", ">= 4.0.2"

gem "kaminari", "~> 1.2", ">= 1.2.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "pry-shell", "~> 0.6"
  gem "standard", "~> 1.29"
  gem "factory_bot_rails", "~> 6.2"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  gem "rspec-rails", "~> 6.0"
  gem "rspec-parameterized", "~> 1.0"
  gem "database_cleaner-active_record", "~> 2.1"
  gem "timecop", "~> 0.9.6"
end
